


Create Table System.IC_IndividualClient
( 
  ID NUMBER(5,0) Generated by Default ON NULL AS Identity MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ,
  NAME Varchar2(255 Byte),
  EMail Varchar2(50 Byte),
  Street Varchar2(50 Byte),
  City Varchar2(50 Byte),
  PostalCode Varchar2(6 Byte)
)



Insert into System.IC_IndividualClient (NAME, EMail, Street, City, PostalCode) values ('Tomasz Wozniak','tom@a.com', 'Malinowa 3','Radom', '09169');  



       CREATE OR REPLACE PROCEDURE SYSTEM.Add_IndividualClient   
    (  
      IC_Name IN Varchar2,
      IC_EMail IN Varchar2,
      IC_Street IN Varchar2,
      IC_City IN Varchar2,
      IC_PostalCode IN Varchar2 
      
    ) AS   
    BEGIN  
       
        Insert INTO  System.IC_IndividualClient (NAME, EMail, Street, City, PostalCode) values (IC_Name,IC_EMail, IC_Street,IC_City, IC_PostalCode); 
    END;   

Select * from System.IC_IndividualClient;
Delete  from System.IC_IndividualClient;




ALTER TABLE System.IC_IndividualClient MODIFY(ID Generated as Identity (START WITH 1));

create or replace PROCEDURE        ClientsList (   
p_clients OUT SYS_REFCURSOR)  
IS  
BEGIN  
OPEN p_clients for Select * from System.IC_IndividualClient;  
END;

CREATE OR REPLACE PROCEDURE System.ClientDetails (
p_clientID IN Number,
p_client OUT SYS_REFCURSOR)  
IS  
BEGIN  
OPEN p_client for Select * from System.IC_IndividualClient where ID= p_clientID;  
END;   


variable id Number :=1;
 Select * from System.IC_IndividualClient where ID= :id


variable mycursor refcursor;
variable id Number;
exec :id :=1;
EXECute System.ClientDetails (:id, :mycursor);
print mycursor;


variable mycursor refcursor;
Execute System.ClientsList ( :mycursor );
print mycursor;


CREATE OR REPLACE PROCEDURE System.ClientUpdate (
p_id System.IC_IndividualClient.ID%Type,
p_name System.IC_IndividualClient.Name%Type,
p_email System.IC_IndividualClient.EMail%Type,
p_street System.IC_IndividualClient.Street%Type,
p_city System.IC_IndividualClient.City%Type,
p_zip System.IC_IndividualClient.PostalCode%Type
)
IS  
BEGIN  
Update  System.IC_IndividualClient 
SET 
Name = p_name,
EMail = p_email,
Street = p_street,
City = p_city,
PostalCode = p_zip
Where ID = p_id;

END;   

CREATE OR REPLACE PROCEDURE SYSTEM.Delete_IndividualClient   
    (  
        IC_ID IN NUMBER
     ) AS   
    BEGIN  
             Delete From  System.IC_IndividualClient Where "ID" = IC_ID;
    END;   
    



